### ISSUE TITLE
Allow to skip sending thread replies to the main channel

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/feature-requests#117]
**Is your feature request related to a problem? Please describe.**
New threads functionality is great, but when multiple threaded discussions are ongoing, the main channel becomes a disaster where it is not possible to understand what comes from where.

Based on the experiese, authors want only 10% of the threaded replies to end up in the main channel so that all main channel members are explicitly notified about it.

**Describe the solution you'd like**
A checkbox close to the threaded message reply field saying "Send the reply to the main channel" or something similar.

**Describe alternatives you've considered**
A setting allowing user to decide whether it is possible to not send threaded replies to the main channel.

**Additional context**

**Comment by engelgabriel** [comment]
Related https://github.com/RocketChat/feature-requests/issues/129

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/14719

**Comment by engelgabriel** [comment]
@zdumitru thanks for the feedback. We are planning to do something like this on the next version of threads. Please, let's concentrate all the feedback and ideas on a single issue: RocketChat/feature-requests#648

Thanks!
