### ISSUE TITLE
API to get all current livechat chats

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/feature-requests#12]
API to get all current livechat chats

![831f154df5a138693f0c34f9b2287aacdab61bcc](https://user-images.githubusercontent.com/1788360/52313920-56185780-29eb-11e9-8cf1-969fe79141c1.png)

**Comment by ariyanatik** [comment]
my rocket account show account is not active. how it solve

**Comment by thangtranse** [comment]
how to get?

**Comment by knrt10** [comment]
On it, will add this.

**Comment by knrt10** [comment]
Fixed by [#14155](https://github.com/RocketChat/Rocket.Chat/pull/14155)

**Comment by renatobecker-zz** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/15155.
