### ISSUE TITLE
Extend REST API for Livechat Inquiry handling

### ISSUE THREAD

**Issue by MrEscaGreenwing** [RocketChat/feature-requests#123]
**Problem**
The use case: The main idea is a support chat. If a user wants to chat he will at first get handled by a bot agent of a bot departmen. As soon as the bot can't help any further with the user's requests, he would forward him to another department containing service workers. Afterwards a service worker takes the forwarded room from the queue of incoming inquiries when he has the time to handle the user.

Therefore I'm trying to use the Livechat feature with Guest Pool Routing and an own adapter for a bot agent. Livechat and adapter communicate both via REST API with the Rocket.Chat Server. As soon as a new room gets opened it's added to the list of open inquiries. Unfortunately there is no possibilty for the adapter to take an inquiry or even access the list via the REST API. Consequently, I can't handle new rooms with the bot agent the way I want to. Especially the room transfer isn't possible as long as the agent hasn't taken the room.

**Solution**
Extending the REST API with an inquiry handling would be quite helpful. According to @renatobecker there need to be at least two new methods. One for listing the current inquiry queue and another for taking a specific inquiry. 
Additionally it would be helpful to have some kind of message telling the agents that a new inquiry was added. So the bot doesn't need to continuously poll if there are any open inquiries. Unless that has nothing to do with the REST API itself, it's just a nice to have.

**Alternative**
Instead of extending the REST API I could also imagine to set different routing methods for each department. So in the bot department new rooms would be handled according to the least amount rule and in the service worker department according to the Guest Pool rule. But I guess it's difficult to handle different routing states when an agent is part of more departmens.

**Additional context**
For a better understanding of the use case I made simplified [gist](https://gist.github.com/MrEscaGreenwing/1fa2b6d2e18c9b5e238c6bd90d8b25a8) of the current implementation.

**Comment by MrEscaGreenwing** [comment]
@renatobecker: I guess I did it. At least the two methods for the REST API calls seem to work like a charm. Shall I open a PR in the Rocket.Chat project and link this issue?

_Edit:_
Because I'm on vacation for a week starting tomorrow I just gave it a shot.

**Comment by renatobecker** [comment]
This is already supported, please take a look at our REST API docs.
Thanks.
