### ISSUE TITLE
Feature Request: User Setting That Allows User To Limit Thread Replies To Threads Only

### ISSUE THREAD

**Issue by jonathan-liss** [RocketChat/feature-requests#129]
Currently all replies to threads appear as text within the conversation flow in chat rooms: 
![image](https://user-images.githubusercontent.com/44573800/59016570-3898b480-884a-11e9-9663-bd9625d6b889.png)

The new feature would create a user setting called "Remove thread replies from main conversation". This would only display the initial thread count within the main chat conversational stream like so: 
![image](https://user-images.githubusercontent.com/44573800/59016611-50703880-884a-11e9-9cd6-dc0d74c93954.png)

The user could then move over to the 'Threads' view if they wanted to see what else has been said within threads but thread replies would stop appearing within the main chat room conversation.

**Comment by engelgabriel** [comment]
We actually want to turn this into a NUMBER and not an ON/OFF options. The idea is that users should be able to choose to see only the first few messages from a thread (default to 3, but 0 would be a valid choice to get the behavior described above).

**Comment by engelgabriel** [comment]
Related https://github.com/RocketChat/feature-requests/issues/117

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/14719

**Comment by engelgabriel** [comment]
@jonathan-liss for the feedback. We are planning to do something like this on the next version of threads. Please, let's concentrate all the feedback and ideas on a single issue: RocketChat/feature-requests#648

Thanks!
