### ISSUE TITLE
Create Rocket.Chat Cloud account error.

### ISSUE THREAD

**Issue by freeJackLi** [RocketChat/feature-requests#133]
"https://cloud.rocket.chat/api/v1/my/set-password"
This url response code 401.
So, I can not create an account.
Please help me.
Thanks!
![set_pass](https://user-images.githubusercontent.com/7724570/59601207-f4ed5700-9135-11e9-8884-faad19dc39a5.png)

**Comment by reetp** [comment]
@rocket-cat close 
I think this user has been advised to contact support @ rocket.chat
