### ISSUE TITLE
"Remind me about this in 1 hour" 

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/feature-requests#14]
Hi, is possible to add feature "Remind me about this" for message like in Slack?

It is very useful.

![remind_me](https://user-images.githubusercontent.com/1219067/43573372-e1c16026-9641-11e8-9ce4-890d875b1292.png)

**Comment by bnowak** [comment]
Quite needed feature
+1

**Comment by Halfi** [comment]
Hi there! @slyk is saying realy useful things. Do you have any estimate? Maybe in v 1.0.0 or 1.1.0?

**Comment by Crazy-Hopper** [comment]
Indeed a must have for busy multitaskers at work. ;)

**Comment by tofixx** [comment]
to simplify the integration, a bot litening on `/remind "for what..." when` could solve that feature...

**Comment by tuxmartin** [comment]
@tofixx no. Command `/remind ...` is uncomfortable. You need copy text of message to _remind_ command.

In Slack you can remind message using menu: https://ctrlv.cz/shots/2019/06/05/IWPj.png

After selected time period, user `slackbot` send you message text and link to original message.

**Comment by tuxmartin** [comment]
@Hudell do you have any updates?

**Comment by johanneshiry** [comment]
+1

**Comment by Tri0L** [comment]
Need this functionality. Not slash command, button.

**Comment by marcin295** [comment]
+1

**Comment by m1nus6066** [comment]
Hi, any updates? We need this functionality!

**Comment by natalazebrova6** [comment]
+1

**Comment by palya-ru** [comment]
+1

**Comment by xeniag1** [comment]
Hello. Any plans to realise that?

**Comment by sergsg60** [comment]
Please do it!

**Comment by maslovsk1y1991** [comment]
Need it!

**Comment by gilissil** [comment]
Last one function that stop me from going to Rocket Chat.

**Comment by Zulkirn** [comment]
Please do it!

**Comment by slyk** [comment]
> Last one function that stop me from going to Rocket Chat.

Yeah, it was for me too.
I needed to start with some chat for my team... and thought that this small feature will be added fast, by analising the release notes seems like many not so important features added all the time this looked like should be in closes milestone.

![people helping me with a problem](https://scottsdalerecovery.com/wp-content/uploads/2016/04/intervention.jpg)
So... **Hello guys, my name is Kirill, I'm using RocketChat and I'm _afraid to open unread messages_** on my phone, because there may be some message that I need to take action from my office, and I will be there in 2 hours. So I left them unread until that time. In other way I should copy/paste those messages to tome todo-app, and that is really annoying :(

**Comment by seroguzova** [comment]
Please make it available!

**Comment by nataliantonova** [comment]
Be handy if it actually did something ;-)

**Comment by kluppov** [comment]
We also need it!

**Comment by s1mbirceva81** [comment]
+1

**Comment by xtayl1ng** [comment]
+1

**Comment by geekgonecrazy** [comment]
Please do not post +1 or me too.  They are not useful.  If you want to actually upvote then hit the thumbs up on the top comment.  This is what actually bumps it up in the stack.

If you are doing it to get notifications.  Please stop.  GitHub has implemented a way to subscribe with out saying a word.  

![A4852797-DE01-489C-A605-9AA62F03719C](https://user-images.githubusercontent.com/51996/64308023-8d3cf000-cf5d-11e9-9bed-4cbecf25fe0e.jpeg)

**Comment by katya11051987** [comment]
I would also like to see such a feature

**Comment by mjovanovic0** [comment]
I laid the foundation for this:

https://github.com/mjovanovic0/rocketchat-remind-app

But, currently, there is a limitation where you cannot bundle NPM dependencies as RCApp dependency and Rocket.Chat does not use `chrono-node` and/or `moment` which I use for parsing phrases into time.

Also, another issue is that it will work in current session only i.e if you close tab/window all set reminders are lost :S

**Comment by Texnarik** [comment]
when will the update be?

**Comment by bobirova** [comment]
Issue is that it will work in current session only

**Comment by tuxmartin** [comment]
Hi, any updates?

**Comment by AlenaShcherbakova** [comment]
My team also need this feature!!!!!)))))))))))

**Comment by reetp** [comment]
People continuously asking for updates please note this is Open Source.

It will get done if someone feels like doing it, or is paid money to do it.

Begging will not help. (My team needs a weeks holiday in South Pacific - anyone want to fix that for me?)

Cash offers might.

https://github.com/RocketChat/Rocket.Chat#donate
https://www.bountysource.com/teams/rocketchat

You could also employ a developer to fix it and contribute the code here which will always be welcomed.

Otherwise you will just have to be patient.

**Comment by tuxmartin** [comment]
@Hudell Hi, any updates?

Do you have any time estimate?

If you add this feature to any upcomming milestone the chance to resolve will increase. I hope :-)
https://github.com/RocketChat/Rocket.Chat/milestones

I understand this is Open Source. But this feature is not even in paid Pro/Enterprise versions https://rocket.chat/pricing

I would like to donate some money for **this feature**.

**Comment by saschafoerster** [comment]
> So... Hello guys, my name is Kirill, I'm using RocketChat and I'm afraid to open unread messages on my phone, because there may be some message that I need to take action from my office, and I will be there in 2 hours. So I left them unread until that time. In other way I should copy/paste those messages to tome todo-app, and that is really annoying :(

Hello, I am Sascha and my team want's to get rid of RocketChat, because one of the most important features is not there. I am also ready to put money somewhere, but where, to get that feature? Does some developer have some time and cost estimate, to integrate a slack-like function or app into rocket chat?

**Comment by tuxmartin** [comment]
Hi, any updates?

**Comment by ugzv** [comment]
This would be some cool feature to have.

**Comment by Tri0L** [comment]
2 years of this feature request without any progress. 
We decided to move to Slack. Finally

**Comment by tuxmartin** [comment]
Are there any updates?

**Comment by geekgonecrazy** [comment]
Initial Scheduler functionality is landing in app engine in 3.8.  So maybe someone can build an app for this :)

**Comment by mjovanovic0** [comment]
Will do :)

**Comment by mjovanovic0** [comment]
I implemented new Scheduler API in my app.

https://github.com/mjovanovic0/rocketchat-remind-app

Now we wait for 3.8 release :)

**Comment by geekgonecrazy** [comment]
This is awesome!! I hope you plan to submit to marketplace.  People will absolutely love this.  I installed on open.rocket.chat and so far the team is impressed. :grin:

**Comment by mjovanovic0** [comment]
Absolutely :)

I already tried to submit it. In that process I found one issue with rc-apps CLI that is resolve now (waiting for new release) to proceed with submit request :)

**Comment by tuxmartin** [comment]
It is great!

Can you please also add reminder to GUI?

I would like to use reminder like in slack for messages:
 https://user-images.githubusercontent.com/1219067/43573372-e1c16026-9641-11e8-9ce4-890d875b1292.png

**Comment by mjovanovic0** [comment]
Will check the possibility for injecting things into context menus. Some UI modifications are possible, not sure if this kind currently is.. (maybe PR to server source? who knows... :D )

**Comment by geekgonecrazy** [comment]
Not sure if adding to message action menu is yet possible.  @d-gubert maybe you or someone from app team can confirm.  :)

**Comment by mjovanovic0** [comment]
I did initial check, currently it's not possible :(

**Comment by saschafoerster** [comment]
😱

**Comment by d-gubert** [comment]
Not possible indeed, and we couldn't fit it into our short-term roadmap for the time being ☹️ but it is definitely something we have imagined for the UIKit to enable

**Comment by mjovanovic0** [comment]
I'm in process to create this option with usage like this:

```ts
await configuration.messageActions.registerActions([new RemindMessageAction('remind-action-id')]);
```

```ts
export class RemindMessageAction implements IMessageAction {
    public id: string;
    public icon: string = 'reply-directly';
    public label: string = 'Remind me about this';
    public context: Array<string> = ['message', 'message-mobile', 'threads'];
    public group: string = 'menu';
    public order: number = 0;

    constructor(id: string) {
        this.id = id;
    }

    public action(event: Event, instance: void): void {
        console.log('action triggered');
    }

    public condition(message: IMessage): void {
        console.log('condition');
    }
}

```

And I'm pretty close to finish it :) Now I only have issue to invoke `MessageAction.addButton(action);` to actually add button to system.

**Comment by jsalatiel** [comment]
When will it be released on market place ? =)

**Comment by mjovanovic0** [comment]
It is submitted, currently in the process of review from RC team.

**Comment by jsalatiel** [comment]
Does it parse  another language  besides english ?

**Comment by mjovanovic0** [comment]
Currently no :(

**Comment by jsalatiel** [comment]
No problem, thanks for working on this app.

**Comment by jsalatiel** [comment]
If eventually we get some UI for it , I think it can be easily  translated =)

**Comment by mjovanovic0** [comment]
Hi all,

First version of Remind Me app is published on official Rocket.Chat Marketplace.

Hope it will serve you well.

Any issue with the app itself, please report it [here](https://github.com/croz-ltd/Rocket.Chat.App-Remind).

**Comment by jsalatiel** [comment]
I still can not install. More like a Rocketchat bug. Even though I am connected to rocketchat cloud services, it says I am not. So i can not download from market place.

**Comment by jsalatiel** [comment]
@mjovanovic0  I was able to install the app, but I am facing some issues. Basically I can trigger the /remind command , but never get the reminder.

If i use /remind me testar algo in 5 minutes, I receive the reply from Rocket.Cat, but no message after 5 minutes.

![image](https://user-images.githubusercontent.com/5522389/104321188-0dfcec00-54c2-11eb-94a7-6a36e4435f9d.png)


The second problem is that if I try to send the remind to a channel , it keeps complaining the Rocket.Cat user is not in the channel, but it is!


I am running RocketChat 3.8.4 in HA mode.

**Comment by tuxmartin** [comment]
@jsalatiel I have the same problem.

https://github.com/croz-ltd/Rocket.Chat.App-Remind/issues

**Comment by jsalatiel** [comment]
> I did initial check, currently it's not possible :(

Can you check if you could add some basic  input ui like the poll extension? /Poll opens an ui that you can customize. so typing /remind would provide basic ui input and more importantly allow translations.

**Comment by tuxmartin** [comment]
Hi, does anyone have anything new?

https://github.com/croz-ltd/Rocket.Chat.App-Remind is missing on Marketplace and it is broken :-(

**Comment by tuxmartin** [comment]
@geekgonecrazy @d-gubert 
Hi, is there any progress?

It is issue from August 2018 with 199 reactions. So people want this.

Is it at any milestone?

**Comment by johncrisp** [comment]
Hi,

> @geekgonecrazy @d-gubert

Please don't @ people - it is unnecessary, and usually the wrong people. Bugs and feature requests are all decided by the Product Management team now, not individual developers.

> Hi, is there any progress?

In the first instance ask the app developer as per this:

https://github.com/RocketChat/feature-requests/issues/14#issuecomment-739238964

https://github.com/croz-ltd/Rocket.Chat.App-Remind/issues

I will ask my colleagues to check with the Product Team to see if they know anything.

Obviously you are more than welcome to submit your own code and we will happily take a look at it.

**Comment by tuxmartin** [comment]
@johncrisp Hi, I'm sorry.  I'm already desperate :-(

**Comment by reetp** [comment]
> @johncrisp Hi, I'm sorry. I'm already desperate :-(

Still don't @ people - it is actually annoying and you will get ignored as likely it is the wrong person. Devs don't make most of the decisions - the Product team does.

It does clearly say above:

> Any issue with the app itself, please report it here.

https://github.com/croz-ltd/Rocket.Chat.App-Remind

This app is not written by Rocket. Please hassle the author, not Rocket.

Alternatively, if it really is that important then employ someone to write it for you. They can liaise with the Rocket team who will undoubtedly assist them.

**Comment by murtaza98** [comment]
Hello All :wave: I'm quite excited to share my new Reminder app over here. I've attempted to add most of the features requested in this issue and I think you guys will like it :smile: . Check out [this doc](https://add-reminders.gitbook.io/docs/) for more info about this app. 

Also, feel free to reach out to me on any below-mentioned channels if you wish to share any feedback or suggestions or even criticism.

Open server of Rocket.Chat: https://open.rocket.chat/direct/murtaza.patrawala
Email: murtaza98.professional@gmail.com
[LinkedIn](https://www.linkedin.com/in/murtaza-patrawala-b17419166/)

**Comment by murtaza98** [comment]
Sharing more about [this app](https://add-reminders.gitbook.io/docs/): it allows you to create personal reminders, reminders for specific channels or users. It also has an option to create reminders for a specific message (@slyk comment [here](https://github.com/RocketChat/feature-requests/issues/14#issuecomment-421095676) was very insightful and you'd find that this app is designed in a way that it provides a quick way to select the time after which you'd like to get reminded about a message). The app also has an option to schedule recurring reminders, thus allowing you to automate some processes. Plus, it is also equipped with some rich features to manage your scheduled reminders, like snoozing, marking as complete, deleting, etc.

**Comment by saschafoerster** [comment]
@murtaza98 I find it very useful. Could you explain a bit more, what kind of data are transferred by installing this app. I saw there are logs transferred, but what else?

**Comment by tuxmartin** [comment]
@murtaza98 Hi, do you have any news? When will this app be available on Rocket.Chat's Marketplace?

**Comment by tuxmartin** [comment]
Solved: https://add-reminders.gitbook.io/docs
