### ISSUE TITLE
Add agent id to assign a room in the rest api

### ISSUE THREAD

**Issue by rparra21** [RocketChat/feature-requests#147]
**Is your feature request related to a problem? Please describe.**
I have two departments with agents to the each one, but I need to assign a room to the agent specific

**Describe the solution you'd like**
In the following endpoint: /api/v1/livechat/room.  I need to add agentid parameter to indicate the agent to whom I want to assign the room.

**Comment by renatobecker-zz** [comment]
Even it's not documented here -> https://rocket.chat/docs/developer-guides/rest-api/livechat/room/index.html, you already can do this:

https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/api/v1/room.js#L18

Please, make sure you're running the latest Rocket.Chat version.
