### ISSUE TITLE
The method /api/v1/livechat/inquiries.list does not work in the rest api

### ISSUE THREAD

**Issue by rparra21** [RocketChat/feature-requests#149]
**Is your feature request related to a problem? Please describe.**
I need to get the list of chats that agent have to assigned but this method /api/v1/livechat/inquiries.list does not work

**Comment by renatobecker-zz** [comment]
Yeah, it won't.
The endpoint you mentioned is to get livechat inquiries, not livechat rooms.

For another question like this, please use our forum.
