### ISSUE TITLE
Android client : beep every minute if there is an unread chat.

### ISSUE THREAD

**Issue by michelpy** [RocketChat/feature-requests#160]
I have users in a noisy environment that may not get the initial notification, so I'd like the Rocket Chat Android client (and possibly all clients, although we are using only Android at the time) to beep every x seconds (possibly 60) when there is an unread message.

Thanks !

**Comment by milton-rucks** [comment]
We appreciate your feedback.
After analyzing the market standards, we decided to don't implement this feature.
Thanks.
