### ISSUE TITLE
Make URLs in topics clickable

### ISSUE THREAD

**Issue by sean-pop** [RocketChat/feature-requests#161]
**Is your feature request related to a problem? Please describe.**
When a room has a URL in the topic, it is frustrating to have to highlight, copy, open a browser, and paste. It would save much time and frustration if the URL was clickable.

**Describe the solution you'd like**
When a URL is added to a room's topic, I'd like to be able to click the URL. This URL should be clickable from both the desktop app and mobile apps.

**Describe alternatives you've considered**
No alternates considered.

**Comment by milton-rucks** [comment]
Feature implemented
