### ISSUE TITLE
Ability to see reported messages

### ISSUE THREAD

**Issue by mahal** [RocketChat/feature-requests#165]
**Problem**
When user clicks "Report" on a message, the admin or owner of a channel doesn't get notified. 

**Solution**
A place to view reported messages: https://github.com/RocketChat/Rocket.Chat/issues/1364

**Describe alternatives you've considered**
A bot that sends messages to those who can react to reported messages.

**Comment by milton-rucks** [comment]
Feature delivered.
It is possible to see it in workspace> moderation panel
