### ISSUE TITLE
alerting for vido conferencing requests

### ISSUE THREAD

**Issue by scoopex** [RocketChat/feature-requests#167]
We often miss jitsi video conferences because they are not alerted in a telephone-like way.
(ring sound, repeated multiple times)

It would be great to have dedicated video conference alert with the following characteristics is someone starts some sort of video conferencing request:

- display a desktop notification in the rocketchat app which points you to the suitable channel
- display a visual alert icon on the suitable channel 
- play a "ring" sound for a defined time of 60 seconds (stop ring after opening the channel, alternatively provide a possibility to stop the alert)
- provide a possibility to configure a dedicated sound and sound duration for video chats

Bonus:
- add a "ignore" button in addition to the "join" button for video conferences, which stops the ring up bell
- add a configuration option for video ringup preferences in addition to the current notification settings

**Comment by milton-rucks** [comment]
Feature implemented.
It is available just for call started in DMs
https://docs.rocket.chat/use-rocket.chat/rocket.chat-conference-call/conference-call-users-guide#incoming-direct-call
