### ISSUE TITLE
It's need screen capture in app

### ISSUE THREAD

**Issue by akong77** [RocketChat/feature-requests#176]
Hello, I like rocket.chat all feature.But in this time. Almost message app like LINE or Whatsapp have screen capture feature on his app. I know windows system has capture software. But it's will good if this feature in app.

**Comment by reetp** [comment]
Just use the OS/phone built in tools?

Whatsapp doesn't have screen capture on Android.

**Comment by akong77** [comment]
I mean PC version.I know android version not screen capture feature.

**Comment by reetp** [comment]
Just use your OS screen capture.

There is no need to reinvent the wheel.

**Comment by akong77** [comment]
I mean rocket.chat pc version. I hope rocket.chat pc version have screen capture in app.

**Comment by reetp** [comment]
> I mean rocket.chat pc version. I hope rocket.chat pc version have screen capture in app.

Yes I understand.

Why not just use the screen capture facilities in your OS?

A lot of effort for not a lot of reward here

**Comment by akong77** [comment]
I know win10 has screen capture this feature. But the win10 screen capture haven't some feature.Like type text on picture. I know that you have no fees, and I have not forced you to do such a function. I just hope that if there is such a function in the future, it will be better. Thank you very much.

**Comment by akong77** [comment]
![screen_capture](https://user-images.githubusercontent.com/6081927/63308855-0a921f00-c327-11e9-884f-cd7b468e88a0.png)
I upload wechat screen capture.Thanks a lot.

**Comment by wreiske** [comment]
@akong77 you might want to check out https://github.com/ShareX/ShareX https://getsharex.com/

**Comment by milton-rucks** [comment]
Thank you for taking the time to share your thoughts and for your suggestion

After thorough review and consideration, we've decided not to move forward with implementing this feature at this time. 

While we won't be implementing this specific request, your feedback is invaluable to us. It helps shape our understanding of our users' needs and informs future updates and enhancements.

Please do continue to share your ideas and feedback with us.
