### ISSUE TITLE
Add a prominent reply button

### ISSUE THREAD

**Issue by thawn** [RocketChat/feature-requests#198]
**Is your feature request related to a problem? Please describe.**
The very useful message threads feature is rarely used because "the reply in thread" option is hidden within the three-dot menu.

**Describe the solution you'd like**
Please add a prominent reply button to existing messages.

**Comment by blunket** [comment]
It appears this is being worked on in https://github.com/RocketChat/Rocket.Chat/issues/15672 🙂

**Comment by antkaz** [comment]
Hi @thawn. Can you close this issue? PR was merged in develop and will be available in the next release

**Comment by thawn** [comment]
That sounds great. Thanks to all who contributed!
