### ISSUE TITLE
Slack import to transfer/download files as well as messages

### ISSUE THREAD

**Issue by robertfromont** [RocketChat/feature-requests#203]
# Problem:
When importing from a Slack export, the channels, users, and message text are all imported, but files that were uploaded to Slack are only referenced by URL. These URLs include a temporary token, so that previews and downloads from within Rocket Chat work, but only for as long as the tokens exist, and only as long as the Slack Workspace exists.

This means that it's not possible to fully migrate from Slack to Rocket Chat; uploaded media and documents are left behind.

# Solution:
It would be better if the Slack importer downloaded the content of URLs starting `https://files.slack.com` and added them to the Rocket.Chat server as uploaded files, updating the message URLs along the way.

It looks like this could be done by adding download/upload code to 
[convertSlackMessageToRocketChat(message)](https://github.com/RocketChat/Rocket.Chat/blob/b5114edff1431e83463da626eeaf46ed6c24adca/app/importer-slack/server/importer.js#L530)

**Comment by robertfromont** [comment]
Sorry if I've posted this issue in the wrong place. The options available when I click _New Issue_ are:

- Bug report
- Custom issue template
- Release
- Report a security vulnerability

As I think I'm asking for something new (that content is downloaded instead of linked), rather than a bug, "Custom issue template" seemed the least wrong option.  Is there a different place for adding feature requests?

And just to confirm I understand, _downloading_ the content (as opposed to linking to it) is not currently supported, right?

**Comment by geekgonecrazy** [comment]
There we go I transfered it.  Yes by default it uses the file links.  It doesn't download.  If the files are deleted on slack end or access is locked down they would stop working

**Comment by robertfromont** [comment]
@geekgonecrazy Thanks.

Is there already something elsewhere in the code that does this? (If I can see some example code, I might be able to get this working...)

**Comment by CantBelieveThisWorks** [comment]
I noticed the same problem. However, after changing the "Storage Type" in the Admin Panel, under "File Upload", from GridFS to Filesystem and pressing the "Download Pending Files" button on the Import Tab, RocketChat started downloading and displaying those files. 
So it seems that the import method works, but that there is some issue with GridFS, preventing the import.

**Comment by robertfromont** [comment]
Thanks! I'll try that...

**Comment by robertfromont** [comment]
That worked for me thanks @CantBelieveThisWorks
