### ISSUE TITLE
Hide message to specifics users in room

### ISSUE THREAD

**Issue by lucasOlivio** [RocketChat/feature-requests#213]
Would be nice to have a function to exclude or hide messages to an user, like when an user is invited to a private room all the messages that are older than the users invitation to the room are hidden from him.

(My first time posting an issue, sorry if was not clear enough)

**Comment by reetp** [comment]
I think has already been asked before??

**Comment by milton-rucks** [comment]
Thank you for taking the time to share your thoughts and for your suggestion

After thorough review and consideration, we've decided not to move forward with implementing this feature at this time.

While we won't be implementing this specific request, your feedback is invaluable to us. It helps shape our understanding of our users' needs and informs future updates and enhancements.

Please do continue to share your ideas and feedback with us.
