### ISSUE TITLE
Feature Request - Ability to mention group/teams of users in a channel

### ISSUE THREAD

**Issue by jwhiteman36** [RocketChat/feature-requests#218]
**Describe the solution you'd like**
I would like to be able to mention a specific group or team of users within a channel. For instance if we had channel where the members consisted of Developers and System Administrators, you could create two groups within the channel that you could mention like `@devs` and `@sysadmins`. The users in the respective groups would then receive a mention notification from that channel. 

**Describe alternatives you've considered**
I have not been able to think of any alternatives to accomplish this. 

**Additional context**
I'm not sure if it would be better to create these groups globally or on a per channel basis. Could possibly integrate with ldap groups?

**Comment by antkaz** [comment]
Great idea! I think that groups should add users, not channels, because there can be many channels, and adding groups in all channels will be difficult

**Comment by milton-rucks** [comment]
Feature developed.
We it is possible to mention Teams.
https://docs.rocket.chat/use-rocket.chat/user-guides/rooms/teams#mention-teams
