### ISSUE TITLE
Dispaly an "unread messsages" count  when the Google Chrome is minimized 

### ISSUE THREAD

**Issue by didacroyo** [RocketChat/feature-requests#285]
**Is your feature request related to a problem? Please describe.**
Windows 10, Google Chrome and RocketChat notification configuration allows to get alerted as soon as a new message is received, but when the user is away and with another  application maximized (having the Google Chrome minimized) it would be great when the user is back to realise that new messages are pending to read, even with the Google Chrome minimized.

**Describe the solution you'd like**
The same unread messages count badge (that can be seen in the Rocketchat tab favicon when the Google Chrome window is open) would be good to be seen having the web browser minimized, or somehow in the tray icon.

**Describe alternatives you've considered**
- Google Chrome Extension
- External program that comunicates with Google Chrome or directly with the RocketChat server (being loged in with your account) that alerts for new messages, displaying the total unread messages)

**Comment by milton-rucks** [comment]
Feature implemented. 

![image](https://github.com/RocketChat/feature-requests/assets/70927132/ad14ace6-9056-437b-a7ba-bd15a39445ab)

Thanks for the feedback.
