### ISSUE TITLE
Add reactions to messages in read-only channels

### ISSUE THREAD

**Issue by ankar84** [RocketChat/feature-requests#305]
**Is your feature request related to a problem? Please describe.**
Users can't add reactions to messages in read-only broadcast channels

**Describe the solution you'd like**
Users should have ability to add reactions to messages in read-only broadcast channels
It is good for feedback on news and other information

**Comment by viktreee** [comment]
+1

**Comment by ankar84** [comment]
That feature introduced to regular read-only channels
![image](https://user-images.githubusercontent.com/4023037/188770815-9f4bd9fd-2256-4547-81aa-cb3758a1811a.png)
