### ISSUE TITLE
Split Administration and Settings

### ISSUE THREAD

**Issue by antkaz** [RocketChat/feature-requests#326]
**Is your feature request related to a problem? Please describe.**
When I open the Administration menu, I need scroll down to setting every time. Also, when the Administration menu is opening the cursor focused to the Search input, but I don't need, because I want open room list (for example). I need scroll up.

![admin-menu](https://user-images.githubusercontent.com/19654261/77910031-d82aa600-72a7-11ea-83e7-25223b1e8032.gif)

**Describe the solution you'd like**
Split administration settings and instance settings into different menus.

![image](https://user-images.githubusercontent.com/19654261/77909168-4f5f3a80-72a6-11ea-8e10-8d5d40320701.png)

**Comment by dougfabris** [comment]
@antkaz We proposed a slightly different solution [#25439](https://github.com/RocketChat/Rocket.Chat/pull/25439) for this, thanks a lot for bringing this up 👍
