### ISSUE TITLE
Possibility for livechat managers to change livechat agents status 

### ISSUE THREAD

**Issue by mar-v** [RocketChat/feature-requests#375]
If an agent forgets to turn the Omnichannel on, or needs to have it toggled off for some reason but he can not do it by himself it would be nice to give the possibility to change his status to a livechat manager role, or create the respective permission. Probably right from the Agents screen in the Omnichannel section. 

<img width="1103" alt="Screenshot 2020-08-10 at 21 24 03" src="https://user-images.githubusercontent.com/47217833/89817052-387ffd00-db50-11ea-821c-c89857c7b646.png">

The options should check the user presence status so a manager could not set the agents status to ON if the agent (his user) is in offline or busy mode.

**Comment by renatobecker** [comment]
It's important to mention that, even a manager has permission to switch the agent's status, it won't work when the `Office Hours` feature is activated and the office hours is closed.

**Comment by renatobecker** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/18571
