### ISSUE TITLE
Message auditing panel

### ISSUE THREAD

**Issue by plmorpheus** [RocketChat/feature-requests#391]
**Is your feature request related to a problem? Please describe.**
I think that this is ridiculous, that in such system there is no messages auditing panel, although in basic version. This is basic functionality in many messengers and lack of this module greatly underestimates the value of this software.

**Describe the solution you'd like**
The message auditing panel should be available to all editions of software, not only for the highest (!) one. It could be ie. a paid module which every can buy in the marketplace if need it, but in my opinion it should be hardcoded in every edition. Not every company needs social integrations, unlimited push messages, SLA, etc. 
Please, consider that!

**Comment by milton-rucks** [comment]
We hear your feedback, but we will keep the Message auditing panel as part of our premium offering.
