### ISSUE TITLE
Automatically convert video uploads to streamable format

### ISSUE THREAD

**Issue by nooblag** [RocketChat/feature-requests#394]
**Is your feature request related to a problem? Please describe.**
When a video is uploaded using Desktop app or through website, if video file is not streamable, it is not playable to end users and sometimes people complain this is a problem. I understand it's not a problem (video file is provided as-is) but it would be nice if Rocket Chat would do auto file conversion when video is not streamable to ensure it is streamable like other chat platforms, etc.

**Describe the solution you'd like**
If a video is uploaded in non streamable format (for example, user uploads AVI file) Rocket Chat autoconverts the upload into a streaming format (for example, h.264 MP4).

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mikerogerz** [comment]
Personally I've already witnessed this, related to my Pixel 4 saving camera videos in x265 (improved compression), and then when I go over to Chrome, I'm not being able to view the videos (only sound). In the mobile app, there are no issues viewing them.

**Comment by nooblag** [comment]
Closing, as gave up on Rocket Chat many years ago.
