### ISSUE TITLE
Push Notifications Bypassing Google Server

### ISSUE THREAD

**Issue by abnormisdictum** [RocketChat/feature-requests#412]
**Is your feature request related to a problem? Please describe.**
From what I understand -and I may be wrong- Rocketchat server even when it is selfhosted, relies on Google and Apple servers to push notifications to a device. This approach may not be the most privacy conscious manner of pushing notifications in that it defeats one of the purposes of a self-hosted solution.

**Describe the solution you'd like**
I have used a self-hosted gotify server in the past to push node-red related notifications to my device. I was wondering if it were possible to make gotify server and client a part of Rocket Chat server and client respectively so that rocketchat could independently push notifications bypassing google and apple servers.

**Describe alternatives you've considered**
I have considered writing my own chat system. But I feel I would merely be reinventing the wheel so many others have already been generous enough to dedicate their time to. Add to that, I am not a proficient programmer in the least. To that end, I was hoping if someone with sufficient skill could guide me or, if they were so inclined, create this feature themselves.

**Additional context**
I am aware that I do have a rather selfish motive to make this request, but would the community indulge me nonetheless. I am sure others would be grateful as I would be. If I am missing some understanding of how push notifications are handled by google and apple, I wouldn't mind an explanation as to how I misunderstood.

Warm Regards

Abnormis Dictum

**Comment by Trans-IP** [comment]
I have an idea that should be simple enough to implement as a workaround of sorts for the whole push notification thing:

- Enable an option in the mobile client that allows a 'push' style notification to be generated for new messages if the application is open but not on in primary display view.   You could then have the app open in the background and still get 'notifications'.  **This seems like a low effort, reasonable compromise.**  Currently you only can see unread messages if the application is on the primary display but there is no notification to go along with it.

- There then could be another core android application that could take this further and silently open/close the app on a timed interval to force checking of new messages using the pull method.  More than likely this is out of the scope of this project but could have a much broader use case for almost any application that pulls notifications.  I guess any macro/automation existing app could work here also.

Both of those things should solve these push issues permanently.

I tested the following with the push gateway disabled on the server:

- App closed on mobile.  Sent message from desktop app or another mobile.  No message arrived until application on mobile was opened.  No notification.

- App open on mobile, primary display.  Sent message from desktop app or another mobile.  Message arrived but no notification.

- App open on mobile, hidden in background running apps and not on primary display or another mobile.  Sent message from desktop app.  Message arrived but no notification but was seen when the rocketchat app was moved to the primary display. 

- Repeated test above but turned off mobile data and wifi before moving the app to the primary display.  The message was still there in the app so it does pull fast enough when in the background and doesn't only pull when you move it to the foreground.  That should be provable in the code (haven't looked).

**Comment by abnormisdictum** [comment]
Thank you for your detailed explanation. But i was more concerned from a privacy point of view. Push notifications go through google servers as I understand it.

What i was wondering was of it were possible to bypass google servers for notification purposes by using gotify, or something along those lines.

**Comment by Trans-IP** [comment]
Exactly!  So what I am suggesting is to NOT use push at all but rather rely on the client side app to do the lifting (pull) and notify you of new messages as if they were push.  This transaction will involve:  client app <-> your server,  with no Google interaction.  

The only thing missing here is the client app at the moment cannot selectively control the types of events that will trigger a notification, specifically any new unread message that appears via pull method.  That is what I am suggesting.  The solution is not without a bit of pain (ie users will need instructions to configure the client side application correctly if the features are developed/enabled) and the app needs to be open in the background for this to work or a macro to start/stop it in the background to get new messages periodically, but it should perform well enough.

**Comment by githlp** [comment]
But if using google servers would be a mandatory for push-notifications how for example does the mail program K9-mail then operate ? K9-mail gives me an audible notification as well as a popup message instantly when new email arrives - no inscription to a special push or play service needed at all - i use GrapheneOS on my mobile phone and this works great so far.

To get independent from firebase and other push-gateways would be a great improvement and feature to change from what ever app to rocket.chat.

**Comment by Trans-IP** [comment]
The K9-mail example is perfect, exactly the thing to try and mimic.

**Comment by abnormisdictum** [comment]
Okay. After all the head banging against both walls and computer screens, it seems there is practically no way to by pass the use of GCM servers to serve notifications from outside of RocketChat. The same is true for all Open Source projects including Matrix Synapse (Elementary client). 

RocketChat and Matrix synapse allows for delivery of the messages via GCM which means they basically act as a proxy so that you need not go through all the horrors of creating an api key and compiling the android app your self. But its GCM none the less.

Now one may ask me why I am being so a*al about this considering all the encryption and "privacy measures" that Google and Apple have "committed" to. Simply because I don't trust them. Today their motivations towards "privacy" is driven by their need for me to trust them enough with my data. The moment that statement is not true, their "commitments" will change, as they already are.

Just wish there was a way to change the GCM server backend to one of my own on a Gotify server right within the android system.
