### ISSUE TITLE
add option to automatically hide livechat when no agent is available

### ISSUE THREAD

**Issue by foss-** [RocketChat/feature-requests#417]
Currently when no agent is available the chat shows in offline mode and allows visitors to leave a message.

**Describe the solution you'd like**
Leaving a message is all nice but it would be great if it was possible to automatically hide the chat, when no agent is available. `agent available = show chat` `no agent available = hide chat`

Hiding / showing should happen automatically without further user / agent or admin interaction.

**Comment by johncrisp** [comment]
Closing this in favour of this as there are too many Issues around on the subject.

https://github.com/RocketChat/Rocket.Chat.Livechat/issues/576
