### ISSUE TITLE
💡: Ability to hide (channel & dm) avatar on mobile apps

### ISSUE THREAD

**Issue by nandgator** [RocketChat/feature-requests#432]
**Is your feature request related to a problem? Please describe.**
I cannot hide the channel avatars, on mobile app...

**Describe the solution you'd like**
Well, I guess the heading speaks for itself.

| RocketChat | Slack |
| --- | --- |
| ![rkcht](https://user-images.githubusercontent.com/38415384/102154191-e274ea80-3e9e-11eb-8b86-d3434c6e34df.jpeg) | ![photo_2020-12-24_17-30-51](https://user-images.githubusercontent.com/38415384/103087526-cba46580-460d-11eb-940e-79cd8335a904.jpg) |

**Environment Information:**
- Rocket.Chat Server Version: 3.9.1
- Rocket.Chat App Version: 4.12.1.2143
- Device Name: itelA46 L5503
- OS Version: android 9

> Moved from https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2711

**Comment by ankar84** [comment]
Web version have `Hide avatar` option, so only mobile version need to implement that.
![image](https://user-images.githubusercontent.com/4023037/106857154-b1f84280-66d0-11eb-87d9-86b1b6c05f16.png)
@diegolmello please take it to your future plans when your team will have time for such feature.
