### ISSUE TITLE
Ringing sound as in a phone call when receiving jitsi meeting request

### ISSUE THREAD

**Issue by raphi59** [RocketChat/feature-requests#446]
**Describe the solution you'd like**
Would be nice if the Notification sound sounds like a phone ringing when you receive an Jitsi Webmeeting Invitation.

**Comment by robertsiedl** [comment]
That would be a very cool feature :-)

**Comment by milton-rucks** [comment]
Feature implemented
https://docs.rocket.chat/use-rocket.chat/rocket.chat-conference-call/conference-call-users-guide#incoming-direct-call
