### ISSUE TITLE
Add all team members to a channel

### ISSUE THREAD

**Issue by bseclier** [RocketChat/feature-requests#463]
Hello, 
When we link a channel to a team, the current members of the team are not registered in the channel. Example :
1. I have a team T1 composed of 2 users U1 and U2.
2. I create a channel C1 which I link to the team T1.
3. U1 and U2 are not registered in C1, even if it is now linked to T1
4. If we check “auto-join”, then, future users registered in T1 (call it T3 and T4) will be registered to C1, but the initial members U1 and U2 are not registered, we have to do it manually.

I think that when a channel is linked (or just when we check auto-join, perhaps), all users of a team should be registered into it, as mentionned in [your documentation](https://docs.rocket.chat/guides/user-guides/teams/teams-channels) : "Add all team members to a channel".

**Comment by johncrisp** [comment]
This looks like a good point.

This forums thread refers:

https://forums.rocket.chat/t/adding-current-members-of-a-team-to-a-newly-created-channel/10987

I will try and get this raised.

**Comment by brtptrs** [comment]
This seems to be solved in 3.15. 
Thank you!!

**Comment by bseclier** [comment]
Yes, thanks to this PR : https://github.com/RocketChat/Rocket.Chat/pull/22056
I'm waiting the 3.15.1 version to update and test it here. I'll close the case after that.
Cheers,

**Comment by johncrisp** [comment]
I am not sure there will be a 3.15.1

Point releases are usually only done for security issues.

**Comment by bseclier** [comment]
We won't update with a .0 version, we had too many problems with this in the past (major features, like jitsi, totally unusable until the .1 version).
Wait and see, then.

**Comment by bseclier** [comment]
Tested in 3.15.1, it works !
Thank you.
