### ISSUE TITLE
Option to disable stack traces in logs

### ISSUE THREAD

**Issue by ankar84** [RocketChat/feature-requests#466]
**Is your feature request related to a problem? Please describe.**
That [comment](https://github.com/RocketChat/Rocket.Chat/pull/22170#issuecomment-849926807) inspired me to that feature request.
It would be very nice to have option to totally disable all stack traces in Rocket Chat logs.
No it's a big problem for docker deployments integrated with ELK stack because of [nature of docker](https://github.com/moby/moby/issues/22920) log system.

**Describe the solution you'd like**
Option **Enable Stack Traces** in **Admin UI - Logs** can solve that problem.
And to all places in code where meteor.error stack trace is launched condition must be added that check if that option is enabled or not.

**Describe alternatives you've considered**
I don't know

**Additional context**
Rocket chat is a corporate grade software with millions of users all over the world and such traces is more expected in young project or something similar.

That traces are useless for Rocket Chat admins, but could be useful to Rocket Chat developers and support, so that option can be easily enabled by support request if it's need to investigate some problem. But in regular usage that stack traces only flood rocket chat logs and don't give admin any useful information of fact.

**Comment by johncrisp** [comment]
So essentially have a 'debug' level for messages?

**Comment by ankar84** [comment]
> So essentially have a 'debug' level for messages?

Exactly! Some debug option for logs, that disabled by default

**Comment by johncrisp** [comment]
We are referring this to the developers and will let you know.

**Comment by ankar84** [comment]
Fixed in version 4.0 I guess
