### ISSUE TITLE
[Feature] Add user uploads size quota

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/feature-requests#469]
**Is your feature request related to a problem? Please describe.**

Now is not possible set user upload quota (in edge situation user can send many files which can consume GB)

**Describe the solution you'd like**

Add possibility to configure uploads quota for user. I.e. user can send 100 MB / 24h

**Describe alternatives you've considered**

**Additional context**

**Comment by johncrisp** [comment]
Nice idea Emil!

**Comment by johncrisp** [comment]
We feel that this is extremely complicated across the different types of deployments.

We will close for now but should others request this we may re-open.

**Comment by emikolajczak** [comment]
Hi,
Could you clarify why deployment type influences on possibility to set user quota? I think this kind of qouta is part of many systems where users can send a files.
