### ISSUE TITLE
Enterprise: create an alert when the maximum number of seats is exceeded

### ISSUE THREAD

**Issue by rcaldeiradev** [RocketChat/feature-requests#470]
**Is your feature request related to a problem? Please describe.**
The Enterprise license stops working when the number of seats is over the maximum, and there is no message about it, it simply stops working. The maximum number of seats also turns into an infinite symbol, like 46 / ∞.

**Describe the solution you'd like**
There should be a clear alert about this (a big red one, like when the cloud registration is pending) or a way to block users from creating new users if the maximum number of seats is reached. It should also display the correct maximum number of seats.

**Describe alternatives you've considered**
We have bought more seats.

**Additional context**

![Selection_146](https://user-images.githubusercontent.com/54914223/121588909-d791b180-ca0c-11eb-980d-6f9421d3188f.png)

**Comment by johncrisp** [comment]
If the licence stops working then this is a bug rather than a NFR and as a customer you should be open and issue immediately with support. Please add this issue link there for reference.

I'll leave this pending for now. Let us know you have a ticket open.

**Comment by johncrisp** [comment]
This is on the road map and it is in the design phase.

It is added internally and this will be closed on release.

**Comment by milton-rucks** [comment]
Thanks for the feedback.

Feature implemented.

The admin receives a banner when the workspace is at 80% of the seat limit and the behavior was changed to not allow add more users instead of removing the license when the seat limit is reached.
