### ISSUE TITLE
[Improvement] Detailed read receipts - storage improvement

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/feature-requests#473]
**Is your feature request related to a problem? Please describe.**
Now detailed read receipts are stored in database as single record for every channel member. It is a problem for big channels. I.e for channel with 100 user for every single message are stored 100 records for read receipts. It results that `rocketchat_message_read_receipt` collection is very huge, several times greater than `rocketchat_message`

**Describe the solution you'd like**
I think it will be optimal and better when for every single message will be stored only one corresponding record, with table of users who read message, in `rocketchat_message_read_receipt`. When user read a message this record could be updated instead of insert new one.

**Describe alternatives you've considered**

**Additional context**

Current solution
```
{
        "_id" : "c456e6qnesqPvugCC",
        "roomId" : "aaa",
        "userId" : "xxx",
        "messageId" : "bbb",
        "ts" : ISODate("2021-05-26T08:24:59.631Z")
}
{
        "_id" : "ucNuXHDeJAGoRDAKD",
        "roomId" : "aaa",
        "userId" : "yyy",
        "messageId" : "bbb",
        "ts" : ISODate("2021-05-26T11:05:07.919Z")
}
{
        "_id" : "WdKQPTi55wMNnw2B6",
        "roomId" : "aaa",
        "userId" : "zzz",
        "messageId" : "bbb",
        "ts" : ISODate("2021-05-26T11:16:46.967Z")
}
{
        "_id" : "SFPHEeHnLB6ER8J5P",
        "roomId" : "aaa",
        "userId" : "ttt",
        "messageId" : "bbb",
        "ts" : ISODate("2021-05-01T07:02:01.690Z")
}
```

Proposed solution

```
{
        "_id" : "SFPHEeHnLB6ER8J5P",
        "roomId" : "aaa",
        "userId" : [
                         "xxx",
                         "yyy",
                         "zzz",
                        "ttt"
        ],
        "messageId" : "7LbpnhHJYjdyLGt5j",
        "ts" : ISODate("2021-05-01T07:02:01.690Z")
}

**Comment by johncrisp** [comment]
We are considering this and will revert.

**Comment by johncrisp** [comment]
Emil, as a follow up the Product Team and Devs took a look at this and just reported back

>We have confirmed this solution is not technically feasible.
> The only way for doing it would be to limit the number of users in a room, but we definitively don't want that.

I'll close this, but follow up with me in open if you have further questions.

**Comment by emikolajczak** [comment]
Hi,
Thanks for quick answer.
Limit users in room is not a solution, still much more read receipts than messages.
I can agree that this can be complex to implementation (especially handle or migrate old and new solution) but i think not impossible.
I understand that this is not a priority and will not be changed.

**Comment by payam124** [comment]
We recently came to the same problem. overloaded MongoDB . After thorough investigation, we came up with rocketchat_message_read_receipt
I wonder to know if any of the following could be considered as workarounds
- feature of disabling read receipts for some rooms. 
- feature of using different MongoDB connection for rocketchat_message_read_receipt
