### ISSUE TITLE
Scaleway Object Storage Support

### ISSUE THREAD

**Issue by rexjohannes** [RocketChat/feature-requests#477]
**Is your feature request related to a problem? Please describe.**
I wanted to use scaleway object storage with s3 because its s3 compatile but that didnt works. 

**Describe the solution you'd like**
Please add scaleway Object Storage as file storage Methode

**Describe alternatives you've considered**
Make amazon s3 option scaleway compatile and not only amazon server

**Additional context**
/

**Comment by johncrisp** [comment]
The S3 system should work with 'compatible' systems eg minio

Please tell us what happened.

Error logs etc etc.
