### ISSUE TITLE
Setting moderators for ALL channels

### ISSUE THREAD

**Issue by flantascience** [RocketChat/feature-requests#487]
Your Rocket.Chat version: 0.44.0

I see I can set moderators for individual channels... is it possible to set moderators for all channels?

**Comment by ankar84** [comment]
Nice to have that moderator role with global scope!

**Comment by debdutdeb** [comment]
Since this issue was created on 2016, it seems to be getting lost in the gh issue list. Anton created a new one so that it stays on the foreground and we can track it better.

Closing in favor of https://github.com/RocketChat/feature-requests/issues/488

**Comment by debdutdeb** [comment]
Everyone (except Anton), you can follow up on this issue/fearture-request here - https://github.com/RocketChat/feature-requests/issues/488

Thanks 🙂
