### ISSUE TITLE
Universal route to open chat with specific user

### ISSUE THREAD

**Issue by krenuser** [RocketChat/feature-requests#495]
**Is your feature request related to a problem? Please describe.**
I want to add "Message me on Rocket.Chat" link to my corporate Email signature.
But as I know, there is now way to get a link with fixed URL like `[Message me on Rocket.Chat](https://chat.company.com/chat/my.login)` that will fit for any user of my organization, because all direct chats have an URL with a specific hash, which means _exact_ direct chat for two _exact_ users (e.g. `https://chat.company.com/direct/QogAdhbB9wE9xixrhgtmHpfB3vWRSeFkzb` and it will differ for any another user that will try to write me directly).

**Describe the solution you'd like**
I think it is possible to create a new route like `/openchat/{login}`, which will be a universal way to:
- open chat with specified user if this chat already exists
- create and open new chat with specified user if it does not exist yet. 

**Describe alternatives you've considered**
https://go.rocket.chat/room?host=company.rocket.chat&rid=user.login&path=direct/user.login

**Additional context**
No additional context.

**Comment by krenuser** [comment]
https://go.rocket.chat/room?host=company.rocket.chat&rid=user.login&path=direct/user.login does what I've wanted.

It's perfect!

UPD: yet it fails while opening web application from this page when current user is not authenticated in chat.
![image](https://user-images.githubusercontent.com/32645945/132806392-d0931507-97b1-4b3d-b626-8e9e2d10300a.png)

**Comment by dudanogueira** [comment]
I can confirm this feature already exists, both using a direct link and using go.rocket.chat

if user is not logged in and logs in, it works as expected. Tested on Open at 4.1.0

Closing this feature request.

Thanks!!!
