### ISSUE TITLE
[Mobile] Shortcut for call in chat header

### ISSUE THREAD

**Issue by ankar84** [RocketChat/feature-requests#509]
**Is your feature request related to a problem? Please describe.**
Now to make a call (Jitsi or BBB) user must go though a pretty long path:
Tap on chat name => Tap Voice Call or Video call

**Describe the solution you'd like**
Web client have a call button right in main chat menu. 
It would be so nice, if Rocket.Chat ReactNative client have such call icon.
That call icon could be located near thread and search icons in chat header.

**Describe alternatives you've considered**
WhatsApp
Web client of Rocket.Chat

**Additional context**
Maybe both audio only call and video call buttons should be there.

cc @diegolmello to inform about that feature request

**Comment by diegolmello** [comment]
Thanks for opening this.
I agree it'd be helpful having an easier way to create calls, but we also need to have in mind the space we have on the header.
While web app has 6+ buttons, channel avatar and name, and there's still a lot of space left, mobile can't do it that way.
Some people would argue adding avatar to the header is more important than Jitsi to UX.
I'll bring this to the next design meeting.
Thank you.

**Comment by milton-rucks** [comment]
Implemented :)
