### ISSUE TITLE
Notification Duration not working for more than 6 seconds

### ISSUE THREAD

**Issue by supervladvik** [RocketChat/feature-requests#522]
Version 3.5.6
My Account -> Presence -> NOTIFICATIONS -> Notification Duration

Allows you to set any time, but actually works from 1 to 6 seconds. If set more than 6 seconds, it is still 6 seconds.

**Comment by dudanogueira** [comment]
Hi @supervladvik ! thanks for sharing this!

This doesn't fit as a feature-request. More like a bug.

Also, this option is no longer available at latest versions. 

As I understand, the notification duration is something that is now handled at the browser or OS level.

Closing for now.

**Comment by supervladvik** [comment]
> Hi @supervladvik ! thanks for sharing this!
> 
> This doesn't fit as a feature-request. More like a bug.
> 
> Also, this option is no longer available at latest versions.
> 
> As I understand, the notification duration is something that is now handled at the browser or OS level.
> 
> Closing for now.

Hi. 
Where i can write about bugs of Rocket.Chat?

I have version 3.5.6 and Rocket.Chat does not offer a newer one, it says that this is the last one.

This is a big problem for us, other users do not respond to my messages, because they do not have time to see the notification.
The tray icon with the number of unread messages looks invisible.
