### ISSUE TITLE
Upgrade to the latest version of EmojiOne

### ISSUE THREAD

**Issue by wreiske** [RocketChat/feature-requests#54]
Migrated from https://forums.rocket.chat/t/upgrade-emojione-from-2-2-6-to-4-0-0/2881

From https://github.com/emojione/emojione#emojione-version-2
> EmojiOne version 2 is no longer supported or distributed.

**Describe the solution you'd like**
Upgrade to the latest version of EmojiOne

There are [a bunch of cool new emoji’s available](https://www.emojione.com/emoji/v4). Can we get emojione upgraded?

Thanks!

**Comment by sampaiodiego** [comment]
closing here per https://github.com/RocketChat/Rocket.Chat/issues/13686#issuecomment-472464573 thx.
