### ISSUE TITLE
Boards

### ISSUE THREAD

**Issue by lucthesloth** [RocketChat/feature-requests#547]
Since the app is focused on small companies and the like, a channel type for "Boards" exactly like Trello would be amazing.

**Comment by debdutdeb** [comment]
How about a Rocket.Chat app to implement this?

**Comment by lucthesloth** [comment]
> How about a Rocket.Chat app to implement this?

I didn't know if Apps were able to do such a thing, didn't dig through the documentation and from what I saw in the marketplace the apps are all using chat integration only ¯\_(ツ)_/¯ I guess since you are saying it then it must be possbile
