### ISSUE TITLE
theme for rocket chat (dark mode/light mode)

### ISSUE THREAD

**Issue by MrPoint1400** [RocketChat/feature-requests#560]
use this [dark mode](https://github.com/pbaity/rocketchat-dark-mode) and improve it.

**Comment by dudanogueira** [comment]
Hi! Please check this [related Issue](https://github.com/pbaity/rocketchat-dark-mode/issues/27)

I'll ask internally about how we are on this front and move this to our feature request repo.

**Comment by marcusxss** [comment]
Any updates on either adopting this extension or the new frontend? Thanks!

**Comment by dusatvoj** [comment]
@engelgabriel @rodrigok any updates?
