### ISSUE TITLE
Clear notifications on mobile when seen on desktop

### ISSUE THREAD

**Issue by Hydrair** [RocketChat/feature-requests#574]
**Is your feature request related to a problem? Please describe.**
When using the ios mobile app and the desktop client, notifications stay on until cleared manually or opening the app.

**Describe the solution you'd like**
When looking at new messages and the unread count on the desktop client gets cleared, remove the notifications on mobile

**Comment by diegolmello** [comment]
It's not possible to do it, at least on iOS.
An entitlement is needed, but Apple stopped providing it a couple of years ago.
Just a few apps like WhatsApp have it, so they can do it.

References:
- https://github.com/TelegramMessenger/Telegram-iOS/blob/48531db09e84d521083bceddeb6373c49dac046c/Telegram/BUILD#L471

- https://developer.apple.com/forums/thread/117939?answerId=612633022#612633022
