### ISSUE TITLE
GIF Support (giphy, tenor,...)

### ISSUE THREAD

**Issue by ogamingSCV** [RocketChat/feature-requests#576]
I don't know how to write this down in long, but I simply have an idea to implement gif paste support for Rocket.Chat, so you can easily search for a gif title and send it in chat.

For this giphy or tenor or something completely different source could be used.

**Comment by ankar84** [comment]
There is already **giphy** and **tenor** apps for Rocket.Chat that do that job.

**Comment by ogamingSCV** [comment]
Oh true I am so sorry. Totally forgot about the Apps :/
