### ISSUE TITLE
Feature request: mention multiple users

### ISSUE THREAD

**Issue by Joffrey54** [RocketChat/feature-requests#611]
There is no 'group definition' in rocketchat
It would be cool to mention role like users. For exemple, some guys have the role 'sys admins', and I want to mention all guys in this role: @sysAdmins

**Comment by milton-rucks** [comment]
Currently, it's possible to group users as teams and mention teams.
https://docs.rocket.chat/use-rocket.chat/user-guides/rooms/teams#mention-teams
