### ISSUE TITLE
[Feature Request] Auto complete or Emoji picker for setting a custom status message

### ISSUE THREAD

**Issue by Erikmitk** [RocketChat/feature-requests#697]
It is possible to set a custom status message and it even supports emojis in it.

But entering them can be tedious. There are ways to enter “regular” emojis via a platforms input methods but there's no way for custom emojis. For entering them you have to manually enter their shortcut/alias and try it out. There's no preview or feature to verify the message prior to setting it.

![image](https://user-images.githubusercontent.com/180686/160782569-603e0b11-d2cb-42bb-8209-bd4edb94b4fc.png)

I think it would be helpful to have the emoji picker at this screen or emoji-auto-complete for adding emoji in a custom status message.

**Comment by dudanogueira** [comment]
Hi Erik!

[Kunalvrm555](https://github.com/Kunalvrm555) just sent this PR the other day :)
https://github.com/RocketChat/Rocket.Chat/pull/24967

**Comment by Erikmitk** [comment]
Woah! Yesssss! All power to @Kunalvrm555! The PR would close this issue. :)
