### ISSUE TITLE
Include emoji reaction results in searches

### ISSUE THREAD

**Issue by xurizaemon** [RocketChat/feature-requests#763]
Feature request, use case as per [18F's "Using emoji for knowledge sharing"](https://18f.gsa.gov/2015/12/08/using-emoji-for-knowledge-sharing/) post.

* ☑️  can search for emoji
* ☑️  can respond to a message with an emoji
* 🔲  search results include messages "tagged" with emoji search term
* ❓ search results should be agnostic about whether a literal emoji or a Rocket.chat `:emoji:` shortcode was entered

Tested on demo.rocket.chat @ 0.47.0-develop today, and I see results when searching for emoji, but I do not see expected search results if the emoji is in a user reaction.

I'm very new to Rocket.chat so the error could be user-side 😉

**Comment by hugocostadev** [comment]
It's fixed in the latest releases
