### ISSUE TITLE
Ringing feature for all kinds of chats

### ISSUE THREAD

**Issue by ghost** [RocketChat/feature-requests#855]
### Description:

Are there any plans of having the ringing feature in all kinds of chats? Not only in 1:1 chats.

Don't know where to ask?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project. I'll move this issue to feature-request repo... 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by hugocostadev** [comment]
BTW, what you mean by rinding feature? As a call?

**Comment by ghost** [comment]
Yes if I call someone or get called in a personal chat my "phone" rings :)
Call feature: https://docs.rocket.chat/use-rocket.chat/rocket.chat-conference-call/conference-call-users-guide
And on the page there is a part `The ringing feature is unavailable in any room except Direct Messages(DMs).` but maybe you have some plans to overcome this unavailability.

**Comment by hugocostadev** [comment]
Got it... I'll check with the Product team if this is in their radar and let you know, thanks :D

**Comment by hugocostadev** [comment]
Reply from PM: 
> it's under discussion, but no estimates related to it at this point

**Comment by ghost** [comment]
Thank you.
