### ISSUE TITLE
Display Username or Channel name in web page title

### ISSUE THREAD

**Issue by MichalFoksa** [RocketChat/feature-requests#857]
**Is your feature request related to a problem? Please describe.**
I use web RocketChat in multiple browser tabs. One tab for a channel or person I chat most with.  
Because each tab has same title (e.g.: “(1) Rocket.Chat”) it becomes difficult to identify which tab corresponds to which user or channel.

Current state:
![RockerChat-name-in-title_narrow-now](https://github.com/RocketChat/feature-requests/assets/10117686/f6e1c758-7c1e-44b2-9e57-0a66fa10d870)

**Describe the solution you'd like**
I suggest adding a username, channel name or discussion name, depending on context, or even user’s avatar into browser title. 
I think it will provide a quick and convenient way to distinguish between different RocketChat instances. 

**Describe alternatives you've considered**
Possible tile formats:
 -	([unread messages]) [username] - Rocket.Chat.  
Narrower tab render:
![RockerChat-name-in-title_narrow](https://github.com/RocketChat/feature-requests/assets/10117686/69e29deb-5317-411e-84db-29c1f659cdd7)
Wider tab render:
![RockerChat-name-in-title_wide](https://github.com/RocketChat/feature-requests/assets/10117686/fd3a8850-1ae8-42f3-8da2-9d7a1491c876)

 -	([unread messages]) [avatar] [username] - Rocket.Chat
 -	([unread messages]) [avatar] [user state] [username] - Rocket.Chat

**Comment by MichalFoksa** [comment]
Feature seems to be implemented by [#30680 - feat: Skip to main content shortcut and useDocumentTitle](https://github.com/RocketChat/Rocket.Chat/pull/30680).

**Comment by milton-rucks** [comment]
Thanks for the feedback.

Feature implemented

![image](https://github.com/RocketChat/feature-requests/assets/70927132/87b99c59-7cc0-4d34-9284-fe396b74ba30)
