### ISSUE TITLE
domain is added to whitelist but user still not allowed to be added

### ISSUE THREAD

**Issue by ghost** [RocketChat/feature-requests#886]
Even though I add a domain to the whitelist eg mydomain.com.au - it is still not letting me add a user with email address user@mydomain.com.au?
![image](https://github.com/RocketChat/feature-requests/assets/120475560/f5a7956b-9faa-4401-bb21-31a1e90d139e)

**Comment by reetp** [comment]
This isn't the right place for this.

Please ask in open.rocket.chat #support and make sure you provide some server information.
