### ISSUE TITLE
Adding date of creation or something similar for a room or a user in the Rocketchat admin panel

### ISSUE THREAD

**Issue by casalsgh** [RocketChat/feature-requests#893]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Adding date of creation or something similar for a room or a user in the Rocketchat admin panel.
Think of it as "Admin wants to know How to display the date of creation or something similar for a room or a user in the Rocketchat admin panel. See image below for more context:
![image](https://github.com/RocketChat/feature-requests/assets/83978645/0c9d6973-a9ee-495a-8670-915bb69dd8b0)

**Describe alternatives you've considered**

**Additional context**
In other works feature request for retrieving a room's creation date.

**Comment by Aseem22** [comment]
@casalsgh please assign.

**Comment by Oliviakelly945** [comment]
Message me

**Comment by heet434** [comment]
I added a column that displays creation dates for Rooms. Does this format work?
<img width="1213" alt="Screenshot 2024-07-02 at 5 37 10 AM" src="https://github.com/RocketChat/feature-requests/assets/118350153/018878c7-7e55-4210-8118-6c69803532b5">

**Comment by heet434** [comment]
Also, where exactly is the user panel you have attached a snapshot of? The user section displayed under the rooms section in the admin panel in my local setup looks something like this:
<img width="1223" alt="Screenshot 2024-07-02 at 5 51 30 AM" src="https://github.com/RocketChat/feature-requests/assets/118350153/e9738861-e920-4625-8a58-d4c05cbb7c38">
<br/>
Should I add a "created at" column in this section?

**Comment by casalsgh** [comment]
> Also, where exactly is the user panel you have attached a snapshot of? The user section displayed under the rooms section in the admin panel in my local setup looks something like this: <img alt="Screenshot 2024-07-02 at 5 51 30 AM" width="1223" src="https://private-user-images.githubusercontent.com/118350153/344837239-e9738861-e920-4625-8a58-d4c05cbb7c38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjAyNDEsIm5iZiI6MTcxOTkxOTk0MSwicGF0aCI6Ii8xMTgzNTAxNTMvMzQ0ODM3MjM5LWU5NzM4ODYxLWU5MjAtNDYyNS04YTU4LWQ0YzA1Y2JiN2MzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxMTMyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGJiMjRiNDc3MDE5ZGJhYzFlMzJiN2FjMzlmMjY2YmQxZWMzMWMyNjNkMThiNTExZWRkY2IyMDgzOTQzNDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bxDHenH0OKQ8L_bh_29d37BiuelYzJHde6LeDM5ic98"> Should I add a "created at" column in this section?

Yes, that would be nice.

**Comment by casalsgh** [comment]
> I added a column that displays creation dates for Rooms. Does this format work? <img alt="Screenshot 2024-07-02 at 5 37 10 AM" width="1213" src="https://private-user-images.githubusercontent.com/118350153/344835380-018878c7-7e55-4210-8118-6c69803532b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjAyNDEsIm5iZiI6MTcxOTkxOTk0MSwicGF0aCI6Ii8xMTgzNTAxNTMvMzQ0ODM1MzgwLTAxODg3OGM3LTdlNTUtNDIxMC04MTE4LTZjNjk4MDM1MzJiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxMTMyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzdmYzczYzQ4MTFiOGRlY2M0ZWYzYmQ5MTM0NGU2ZTM4MzYyY2MzZWNhM2ViZWQ5Y2E0M2UyMTc3MzA4M2I4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OiYyM3RgpaJ6fZVivDjco4SLR-LCLhF-qkJJTTLW97s">

Looks good and would already be an informative addition

**Comment by heet434** [comment]
> > Also, where exactly is the user panel you have attached a snapshot of? The user section displayed under the rooms section in the admin panel in my local setup looks something like this: <img alt="Screenshot 2024-07-02 at 5 51 30 AM" width="1223" src="https://private-user-images.githubusercontent.com/118350153/344837239-e9738861-e920-4625-8a58-d4c05cbb7c38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjAyNDEsIm5iZiI6MTcxOTkxOTk0MSwicGF0aCI6Ii8xMTgzNTAxNTMvMzQ0ODM3MjM5LWU5NzM4ODYxLWU5MjAtNDYyNS04YTU4LWQ0YzA1Y2JiN2MzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxMTMyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGJiMjRiNDc3MDE5ZGJhYzFlMzJiN2FjMzlmMjY2YmQxZWMzMWMyNjNkMThiNTExZWRkY2IyMDgzOTQzNDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bxDHenH0OKQ8L_bh_29d37BiuelYzJHde6LeDM5ic98"> Should I add a "created at" column in this section?
> 
> Yes, that would be nice.

I noticed that when you click on a particular user, it already displays the user creation / joining date on the right side popup. So currently I have added a PR for "created at" column in the RoomsTable only. Thanks!

**Comment by casalsgh** [comment]
Requested a review on recent PR and soon should have some news. thanks!

**Comment by reetp** [comment]
Any news on this Gabriel?

**Comment by casalsgh** [comment]
Thanks Heet434! your PR was merged and will be on 6.12.0 version; really happy to see it and will be closing this ticket for now

**Comment by reetp** [comment]
Just wondering if @heet434 could do a similar thing for the users table?

I have seen a request for that on open.rocket.chat 

https://open.rocket.chat/channel/support?msg=TvS3LCGirN3gpP43B

I believe it used to be implemented here but no idea how as I can see no PR associated with it:

https://github.com/RocketChat/Rocket.Chat/issues/3013#issue-150548926

**Comment by heet434** [comment]
> Just wondering if @heet434 could do a similar thing for the users table?
> 
> I have seen a request for that on open.rocket.chat
> 
> https://open.rocket.chat/channel/support?msg=TvS3LCGirN3gpP43B
> 
> I believe it used to be implemented here but no idea how as I can see no PR associated with it:
> 
> [RocketChat/Rocket.Chat#3013 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/3013#issue-150548926)

Sure @reetp I'll start working on it.
