### ISSUE TITLE
App to report a post

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/feature-requests#94]
App idea (not BOT) transferred from RocketChat/Rocket.Chat#10174

From @Molle500

There should be a button (preferably in the gear wheel menu) where users can report a post.

I´m not 100% sure how the solution should work but my idea is: a new channel which only Moderators and Admins can access. There a bot (cat bot?) should post a text something like this.

and @designgurudotorg

Working SMS into the chat experience across the app would be amazing, and open up RC to a whole world of dumb phones (plus enable us to code bots to interact with SMS within chatrooms)...

**Comment by marco-aa** [comment]
I looked around for differnt discussions/issues about "Report a Message" 

Collection of APP/Bot ideas - idea for a reporting - closed
https://github.com/RocketChat/Rocket.Chat/issues/10174

Feature liste created based on #10174 App to report a post - open
https://github.com/RocketChat/feature-requests/issues/94

Option to report abuse of message - still open
https://github.com/RocketChat/Rocket.Chat/issues/503

Wrong text when reporting a message - still open
https://github.com/RocketChat/Rocket.Chat/issues/14514

Report abuse - removed - closed
https://github.com/RocketChat/Rocket.Chat/issues/8999

add a report post button - closed
https://github.com/RocketChat/Rocket.Chat/issues/3514

I hope this can be usefull

**Comment by marco-aa** [comment]
> There should be a button (preferably in the gear wheel menu) where users can report a post.

This button is availible in my Rocket.Chat 1.2.1. It gives you a popup box for a comment and you can send it.
If you see in the logfile the message is reported as you can see here:
https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/reportMessage.js

At the moment i have a look if i can intercept this message with a bot and send it to a room, because there is no UI or storage or i could not find it ;)

**Comment by mahal** [comment]
@marco-aa There is no UI for it. Did you find a way to intercept the message and send it to a room? 
The issue for the missing UI is here https://github.com/RocketChat/Rocket.Chat/issues/1364

**Comment by Sing-Li** [comment]
Finally implemented as part of Moderation Console  https://github.com/RocketChat/Rocket.Chat/pull/27961
